---

- name: Wait some minutes for report
  pause:
    minutes: 3

- name: Facts public EC2 instance
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Role": bastion
      instance-state-name: running
  register: public_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Role": datanode
      instance-state-name: running
  register: datanode_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Role": master
      instance-state-name: running
  register: master_private_ec2_facts

- name: Clean content inventories file
  shell: echo " " > "{{ path_hosts_group }}"/hosts

- name: Clean content of datanode inventories file
  shell: echo " " > "{{ path_hosts_group }}"/namenode


- name: Write Ambari server
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[ambariserver]"

- name: Write Ambari server
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
  with_together: 
        - "{{ (master_private_ec2_facts.instances|map(attribute='tags.Host')|list)[0] }}"
        - "{{ (master_private_ec2_facts.instances|map(attribute='private_ip_address')|list)[0] }}" 

- name: Write Namenodes
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[masternodes]"


- name: Write Namenodes
  lineinfile:
    dest: "{{ path_hosts_group }}/namenode"
    insertafter: EOF
    state: present
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
  with_together: 
        - "{{ master_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ master_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 


- name: Merger namenodenode file to host inventories
  shell: 'cat {{ path_hosts_group }}/namenode >> {{ path_hosts_group }}/hosts'


- name: Write Datanodes
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[datanodes]"

- name: Write Datanodes
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ datanode_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ datanode_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 


- name: Change ambari server IP
  lineinfile:
    dest: "group_vars/all.yaml"
    regexp: '^var_ambari_server: '
    line: 'var_ambari_server: {{ item.0 }}'
  with_together: 
        - "{{ (master_private_ec2_facts.instances|map(attribute='private_ip_address')|list)[0] }}" 

- name: Update basion host
  lineinfile:
    dest: "group_vars/all.yaml"
    regexp: '^bastion_ip: '
    line: 'bastion_ip: {{ item.0 }}'
  with_together: 
        - "{{ (public_ec2_facts.instances|map(attribute='public_ip_address')|list)[0] }}" 

- name: Write ssh common args group
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[all:vars]"        

- name: Wite ssh common args
  shell: echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> "{{ path_hosts_group }}"/hosts    