version: '2'
services:
    zookeeper-1:
        image: confluentinc/cp-zookeeper:6.2.4
        hostname: zookeeper-1
        restart: always
          #ports:
          #    - 2182:2182
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 21
            ZOOKEEPER_CLIENT_PORT: 22181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_MAXCLIENTCNXNS: 0
            ZOOKEEPER_AUTHPROVIDER.1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
            ZOOKEEPER_REQUIRECLIENTAUTHSCHEME: sasl
            ZOOKEEPER_JAASLOGINRENEW: 3600000
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/server_jaas.conf
            ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
        network_mode: host
        volumes:
            - ./secrets:/etc/kafka/secrets
            - ./zk1-data:/var/lib/zookeeper
        extra_hosts:
            - "moby:127.0.0.1"
    zookeeper-2:
        image: confluentinc/cp-zookeeper:6.2.4
        hostname: zookeeper-2
        restart: always
          #ports:
          #    - 2183:2183
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 21
            ZOOKEEPER_CLIENT_PORT: 32181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_MAXCLIENTCNXNS: 0
            ZOOKEEPER_AUTHPROVIDER.1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
            ZOOKEEPER_REQUIRECLIENTAUTHSCHEME: sasl
            ZOOKEEPER_JAASLOGINRENEW: 3600000
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/server_jaas.conf
            ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
        network_mode: host
        volumes:
            - ./secrets:/etc/kafka/secrets
            - ./zk2-data:/var/lib/zookeeper
        extra_hosts:
            - "moby:127.0.0.1"
    zookeeper-3:
        image: confluentinc/cp-zookeeper:6.2.4
        hostname: zookeeper-3
        restart: always
          #ports:
          #  - 2184:2184
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 21
            ZOOKEEPER_CLIENT_PORT: 42181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_MAXCLIENTCNXNS: 0
            ZOOKEEPER_AUTHPROVIDER.1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
            ZOOKEEPER_REQUIRECLIENTAUTHSCHEME: sasl
            ZOOKEEPER_JAASLOGINRENEW: 3600000
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/server_jaas.conf
            ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
        network_mode: host
        volumes:
            - ./secrets:/etc/kafka/secrets
            - ./zk3-data:/var/lib/zookeeper
        extra_hosts:
            - "moby:127.0.0.1"
    kafka-1:
        image: confluentinc/cp-kafka:6.2.4
        hostname: broker-1
        container_name: kafka-1
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
              #ports:
              #- 19092:19092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:19092
            KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://192.168.50.186:19092
            KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/server_jaas.conf
            KAFKA_SUPER_USERS: User:admin
        network_mode: host
        volumes:
            - ./secrets:/etc/kafka/secrets
            - ./kafka1-data:/var/lib/kafka/data
        extra_hosts:
            - "moby:127.0.0.1"
    kafka-2:
        image: confluentinc/cp-kafka:6.2.4
        hostname: broker-2
        container_name: kafka-2
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
              #ports:
              # - 29092:29092
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:29092
            KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://192.168.50.186:29092
            KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/server_jaas.conf
            KAFKA_SUPER_USERS: User:admin
        network_mode: host
        volumes:
            - ./kafka2-data:/var/lib/kafka/data
            - ./secrets:/etc/kafka/secrets
        extra_hosts:
            - "moby:127.0.0.1"
    kafka-3:
        image: confluentinc/cp-kafka:6.2.4
        hostname: broker-3
        container_name: kafka-3
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
              #ports:
              # - 39092:39092
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:39092
            KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://192.168.50.186:39092
            KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/server_jaas.conf
            KAFKA_SUPER_USERS: User:admin
        network_mode: host
        volumes:
            - ./secrets:/etc/kafka/secrets
            - ./kafka3-data:/var/lib/kafka/data
        extra_hosts:
            - "moby:127.0.0.1"
