#cloud-config

hostname: localhost
#主机名要改 上newrelic

coreos:
  units:
    - name: setup.service
      command: start
      content: |
          [Unit]
          Description=setup service
          [Service]
          TimeoutStartSec=0
          ExecStart=/bin/sh -c "echo 'started'>>/tmp/test.log;curl -sL http://192.168.1.4/config/pxe.sh | sudo bash - "
    - name: static.network
      content: |
          [Match]
          Name=enp2s0

          [Network]
          Address=192.168.1.101/24
          Gateway=192.168.1.1
      
