---
- name: fetch the Ambari yum repo (RedHat)
  when: ansible_os_family == 'RedHat'
  command: 'wget -nv {{ var_ambari_version }} -O /etc/yum.repos.d/ambari.repo'
- name: install the ambari agent (RedHat)
  when: ansible_os_family == 'RedHat'
  yum: name=ambari-agent state=latest
- name: configure the ambari agent
  command: 'sed -i s/hostname=.*/hostname={{ var_ambari_server }}/ /etc/ambari-agent/conf/ambari-agent.ini'
- name: Disable ssl verify
  lineinfile: 
          dest: /etc/python/cert-verification.cfg
          regexp: '^verify='
          line: 'verify=disable'

- name: Disable ambari agent ssl verify
  lineinfile: 
          dest: /etc/ambari-agent/conf/ambari-agent.ini
          regexp: '^ssl_verify_cert='
          insertafter: EOF
          line: |
            ssl_verify_cert=0
            force_https_protocol=PROTOCOL_TLSv1_2
- name: check if services is exists
  command: /etc/init.d/ambari-agent status
  ignore_errors: yes
  register: service_status_agent
- name: Stop Ambari agent
  command: /etc/init.d/ambari-agent stop
  when: "service_status_agent.rc == 0"
- name: start the ambari agent
  command: 'ambari-agent start'