version: '2'
services:
  nginx:
    image: "nginx"
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx:/etc/nginx
      - /app/web:/app/web
    restart: "always"
    network_mode: "host"
