---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic
  name: es-config
  labels:
    app: elasticsearch
    role: es
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}.es-svc.elastic.svc.cluster.local
    path.data: ${PATH_DATA}
    path.logs: ${PATH_LOGS}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${NODE_LIST} 
    network.host: 0.0.0.0
    node:
      master: true
      data: true
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
    xpack.monitoring.collection.interval: 30s
