version: '2'
services:
  filebeat:
    image: filebeat
    hostname: filebeat
    container_name: filebeat
    restart: always
    volumes:
      - /home/azureuser/filebeat/filebeat.yml:/filebeat.yml
      - /var/lib/docker/containers:/opt
    links:
      - logstash
  logstash:
    image: logstash
    hostname: logstash
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "5000:5000"
      - "5044:5044"
    volumes:
      - /home/azureuser/logstash/logstash.conf:/opt/logstash/conf/logstash.conf
    links:
      - elasticsearch
    command: logstash -f /opt/logstash/conf/logstash.conf

  elasticsearch:
    image: elasticsearch
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
     - LS_JAVA_OPTS=-Xmx256m -Xms256m
    restart: always
    ports:
     - "9200:9200"

  kibana:
    image: kibana
    hostname: kibana
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    links:
      - elasticsearch
    ports:
      - "5601:5601"
