groups:
  - name: api_alert
    rules:
    - alert: api接口异常
      expr: floor(probe_success{job="api_resources"}) != 1
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "[{{ $labels.desc }}],api接口连接异常,告警初始时长为1分钟."

