groups:
  - name: kafka_alert
    rules:
    - alert: kafka连接异常
      expr: floor(up{job="kafka_resources"}) != 1
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "[{{ $labels.desc }}],kafka连接异常,告警初始时长为1分钟."

