groups:
  - name: nginx_alert
    rules:
    - alert: nginx异常
      expr: floor(up{job="nginx_resources"}) != 1
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "[{{ $labels.desc }}],nginx异常,告警初始时长为1分钟."

