version: '2'

services:

  nginx:
    build: nginx/
    ports:
      - "8882:8882"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - kibana
      - jenkins

  jenkins:
    build: jenkins/
    volumes:
      - /opt/jenkins:/var/jenkins_home

  elasticsearch:
    build: elasticsearch/
    volumes:
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "8881:8881"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    depends_on:
      - elasticsearch
