version: '2'
services:
  memcached:
    container_name: "memcached"
    image: "memcached"
    mem_limit: 512M
    command: memcached -m 512M -p 11211
    ports:
      - "11211:11211"
    restart: "always"
    network_mode: "host"
