version: '2'
services:
  redis:
    image: redis 
    container_name: redis
    volumes:
      - "/app/redis-data:/data"
      - "./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    mem_limit: 2000M
    #command: memcached -m 1500M
    restart: "always"
    network_mode: host
