# Description
# ===========
# This is helper task to delete test resource group

- name: delete test resource group
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: "{{ resource_group_name }}"
    resource_group_secondary: createvmsubnetin2ndrg2
  tasks:
  - name: delete test resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      force: True
      state: absent

  - name: delete second resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_secondary }}"
      force: True
      state: absent
