---
#- hosts: sparkpad_production_web_cc
#  tasks:
#    - name: git pull for CC
#      command: "git pull origin master chdir=/app/web/www" 

- hosts: sparkpad_production_web_fe
  tasks:
    - name: git pull for FE
      command: "git pull origini dev chdir=/app/web/www" 
    - name: remove cache
      shell: "rm -rf /app/vagrant/app/src/ZKF3.0-Front/app/cache/*"
      args:
        executable: /bin/bash
      ignore_errors: yes
#- hosts: sparkpad_production_web_cdmp
#  tasks:
#    - name: git pull for CRM
#      command: "git pull origin zkf3.0 chdir=/app/web/crm"
#    - name: git pull for DE
#      command: "git pull origin dev chdir=/app/web/de"
#    - name: git pull for PMT
#      command: "git pull origin zkf3.0 chdir=/app/web/pmt"
#    - name: git pull for mkt
#      command: "git pull origin zkf-marketing-dev chdir=/app/web/mkt"  
