---
- hosts: sparkpad_production_web_cc
  tasks:
    - name: git pull for CC
      command: "pwd chdir=/app/web/www" 

- hosts: sparkpad_production_web_fe
  tasks:
    - name: git pull for FE
      command: "pwd chdir=/app/web/www" 
    - name: remove cache
      shell: "/usr/bin/ls -lrt /app/vagrant/app/src/ZKF3.0-Front/app/cache/*"
      args:
        executable: /bin/bash
      ignore_errors: yes

- hosts: sparkpad_production_web_cdmp
  tasks:
    - name: git pull for CRM
      command: "pwd chdir=/app/web/crm"
    - name: git pull for DE
      command: "pwd chdir=/app/web/de"
    - name: git pull for PMT
      command: "pwd chdir=/app/web/pmt"
    - name: git pull for mkt
      command: "pwd chdir=/app/web/mkt"  
