version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - /mnt/raid0/data/redis/redis0:/bitnami/redis/data
      - /mnt/raid0/conf/rediscluster/7000/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    ports:
      - '7000:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
        #- 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_NODES=redis-node-0' 

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - /mnt/raid0/data/redis/redis1:/bitnami/redis/data
      - /mnt/raid0/conf/rediscluster/7001/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-0
    ports:
      - '7001:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
        #- 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_NODES=redis-node-1'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - /mnt/raid0/data/redis/redis2:/bitnami/redis/data
      - /mnt/raid0/conf/rediscluster/7002/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-1
    ports:
      - '7002:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
        #- 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_NODES=redis-node-2'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - /mnt/raid0/data/redis/redis3:/bitnami/redis/data
      - /mnt/raid0/conf/rediscluster/7003/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-2
    ports:
      - '7003:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
        #- 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_NODES=redis-node-3'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - /mnt/raid0/data/redis/redis4:/bitnami/redis/data
      - /mnt/raid0/conf/rediscluster/7004/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-3
    ports:
      - '7004:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_NODES=redis-node-4'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - /mnt/raid0/data/redis/redis5:/bitnami/redis/data
      - /mnt/raid0/conf/rediscluster/7005/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    ports:
      - '7005:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
        #- 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_NODES=redis-node-5'
      ###priority, must behind node
      #- 'REDIS_CLUSTER_REPLICAS=1'
      #- 'REDIS_CLUSTER_CREATOR=yes'
      #- 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.1.110'
      #- 'REDIS_CLUSTER_ANNOUNCE_PORT=6379'
      #- 'REDIS_CLUSTER_DYNAMIC_IPS=no'


volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

