---
- hosts: sparkpad_production_web_cdmp
  tasks:
    - name: git pull for mkt 
      command: "git pull origin master chdir=/app/web/mkt/sites/default/"

#    - name: up db 
#      command: "drush updb -y chdir=/app/web/mkt/sites/default/"
#      environment:
#        PATH: /app/php/bin:/app/memcached/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/app/php/bin:/app/mysql/bin:/home/spark/.local/bin:/home/spark/bin:/app/php/bin
#
#    - name: drush cc all
#      command: "drush cc all -v chdir=/app/web/mkt/sites/default/"
#      environment:
#        PATH: /app/php/bin:/app/memcached/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/app/php/bin:/app/mysql/bin:/home/spark/.local/bin:/home/spark/bin:/app/php/bina- hosts: spa
#
- hosts: sparkpad_production_web_erp_1
  tasks:
   - name: git pull for New MKT 
     command: "git pull origin master chdir=/app/code/mkt/"
