version: '2'
services:
    mysql:
      image: mysql:5.7.13
      container_name: mysql
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - /app/mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=jinjin123
      network_mode: host
